version: "3.7"
services:
 flask-redis:
    image: "redis:alpine"
    container_name: flask_base_redis_container
    command: redis-server --requirepass IRt8xEQEXonYqm9CoRDXCnENkzQjlMWr
    ports:
     - "6379:6379"
    volumes:
      - '$PWD/redis-data:/var/lib/redis'
      - '$PWD/redis.conf:/usr/local/etc/redis/redis.conf'
